MvcUser/MvcUser/Models/ErrorViewModel.cs
using System;

namespace MvcUser.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcUser/MvcUser/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using MvcUser.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUser.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MvcUserContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<MvcUserContext>>()))
            {
                // Look for any movies.
                if (context.User.Any())
                {
                    return;   // DB has been seeded
                }

                context.SaveChanges();
            }
        }
    }
}

MvcUser/MvcUser/Models/User.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUser.Models
{
    public class User
    {
        public int Id { get; set; }
        [Required] 
        public int UserNo { get; set; }
        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string UserFirstName { get; set; } 
        public string UserLastName { get; set; }
        [Required]
        public string UserPassword { get; set; }
    }
}

MvcUser/MvcUser/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcUser.Models;

namespace MvcUser.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcUser/MvcUser/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcUser.Data;
using MvcUser.Models;

namespace MvcUser.Controllers
{
    public class UsersController : Controller
    {
        private readonly MvcUserContext _context;

        public UsersController(MvcUserContext context)
        {
            _context = context;
        }

        // GET: Users  
        [HttpPost] public async Task<IActionResult> IndexAsync(string searchString, bool notUsed) {
            //return "From [HttpPost]Index: filter on " + searchString; 
            var users = from m in _context.User select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s =>
                s.UserFirstName.Contains(searchString) ||
                s.UserLastName.Contains(searchString) ||
                s.UserNo.ToString().Contains(searchString));
            }
            return View(await users.ToListAsync());
        }

        public async Task<IActionResult> Index(string id) { 
            var users = from m in _context.User select m;
            if (!String.IsNullOrEmpty(id)) {
                users = users.Where(s => 
                s.UserFirstName.Contains(id) ||
                s.UserLastName.Contains(id) ||
                s.UserNo.ToString().Contains(id));
            } 
            return View(await users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserNo,UserFirstName,UserLastName,UserPassword")] User user)
        { 
                if (ModelState.IsValid)
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(user);  
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserNo,UserFirstName,UserLastName,UserPassword")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            User user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        } 
    }
}

MvcUser/MvcUser/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcUser/MvcUser/Views/Home/UserSignIn.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/sign-in/">
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap core CSS


    <link href="signin.css" rel="stylesheet">  -->
</head>

<body class="text-center">
    <form class="form-signin">
        <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
</body>
</html>

MvcUser/MvcUser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Users" asp-action="Index">Test App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - azatates7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html> 

MvcUser/MvcUser/Views/Users/Create.cshtml
@model MvcUser.Models.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserNo" class="control-label"></label>
                <input asp-for="UserNo" class="form-control" />
                <span asp-validation-for="UserNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserFirstName" class="control-label"></label>
                <input asp-for="UserFirstName" class="form-control" />
                <span asp-validation-for="UserFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLastName" class="control-label"></label>
                <input asp-for="UserLastName" class="form-control" />
                <span asp-validation-for="UserLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserPassword" class="control-label"></label>
                <input asp-for="UserPassword" class="form-control" />
                <span asp-validation-for="UserPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcUser/MvcUser/Views/Users/Delete.cshtml
@model MvcUser.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserFirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserFirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserLastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserLastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserPassword)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserPassword)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcUser/MvcUser/Views/Users/Details.cshtml
@model MvcUser.Models.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserFirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserFirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserLastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserLastName)
        </dd>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserPassword)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserPassword)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcUser/MvcUser/Views/Users/Edit.cshtml
@model MvcUser.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserNo" class="control-label"></label>
                <input asp-for="UserNo" class="form-control" />
                <span asp-validation-for="UserNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserFirstName" class="control-label"></label>
                <input asp-for="UserFirstName" class="form-control" />
                <span asp-validation-for="UserFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLastName" class="control-label"></label>
                <input asp-for="UserLastName" class="form-control" />
                <span asp-validation-for="UserLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserPassword" class="control-label"></label>
                <input asp-for="UserPassword" class="form-control" />
                <span asp-validation-for="UserPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcUser/MvcUser/Views/Users/Index.cshtml
@model IEnumerable<MvcUser.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Users" asp-action="Index">
    <p> Search: <input type="text" name="SearchString"> <input type="submit" value="Filter" /> </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserPassword)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserPassword)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>